"""รูปยาชั่วคราว (วาดด้วยโค้ด) จนกว่าจะได้รูปจริง — ได้รูปจริงแล้วให้วางทับ art/items/herb-potion-*.png
สร้าง 16px แล้วขยาย ×2 ×4 แบบลงตัว:  python tools/placeholder_potion.py
"""
from pathlib import Path
from PIL import Image

# . = โปร่งใส  o = เส้นขอบ  c = จุกไม้  C = จุกเงา  g = ขวด/ยาเขียว  G = เขียวเข้ม  l = แสงสะท้อน  w = ขาวแวว
ART = """
......oooo......
.....occCo......
.....oCCCo......
......oooo......
......oggo......
.....oggggo.....
....ogglgggo....
...oggwlggGGo...
...oglgggggGo...
...oggggggGGo...
...ogggggGGGo...
...oGgggGGGGo...
....oGGGGGGo....
.....oooooo.....
................
................
"""
COLORS = {
    "o": (40, 22, 18, 255), "c": (176, 118, 64, 255), "C": (122, 76, 38, 255),
    "g": (92, 196, 104, 255), "G": (46, 132, 70, 255), "l": (168, 236, 150, 255), "w": (245, 255, 240, 255),
}

rows = [r for r in ART.strip("\n").split("\n")]
img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
for y, row in enumerate(rows):
    for x, ch in enumerate(row):
        if ch in COLORS:
            img.putpixel((x, y), COLORS[ch])

out = Path(__file__).resolve().parent.parent / "art" / "items"
img.save(out / "herb-potion-16.png")
img.resize((32, 32), Image.NEAREST).save(out / "herb-potion-32.png")
img.resize((64, 64), Image.NEAREST).save(out / "herb-potion-64.png")
print("ok")
